In [1]:
import pandas as pd
import matplotlib.pyplot as plt

# Load dataset
df = pd.read_csv("Job_Market_India_with_Skills.csv")

# Clean column names
df.columns = df.columns.str.lower().str.strip()

df.head()

,record_date,company_name,job_role,experience_level,city,salary_inr,demand_index,remote_option_flag,salary_trend_pct,skills_required
0,11/22/2015,State Bank of India,Product Manager,0-1 years,Noida,1615767,71,0,8.72,"Communication, Problem Solving, Team Work"
1,11/22/2015,Hindustan Unilever,Frontend Developer,0-1 years,Hyderabad,790163,81,0,5.26,"HTML, CSS, JavaScript, UI/UX"
2,11/22/2015,Bharat Petroleum,Software Engineer,5-8 years,Bangalore,1104756,94,0,0.08,"Java, Python, Data Structures, OOPs"
3,11/22/2015,HDFC Bank,UI/UX Designer,5-8 years,Mumbai,905086,94,1,8.22,"Communication, Problem Solving, Team Work"
4,11/22/2015,Maruti Suzuki,Data Analyst,1-3 years,Bangalore,578687,35,0,11.54,"SQL, Excel, Power BI, Python"

In [2]:
# Total active job postings
total_jobs = len(df)

print("Total Job Demand (Active Postings):", total_jobs)

Total Job Demand (Active Postings): 30000

In [4]:
top_companies = (
    df['company_name']
    .value_counts()
    .reset_index()
)

top_companies.columns = ['Company_name', 'Hiring_Count']

# Top 10 companies
top_10_companies = top_companies.head(10)

top_10_companies

          Company_name  Hiring_Count
0    Adani Enterprises          1004
1      Capgemini India          1002
2                Paytm           998
3   Hindustan Unilever           978
4  State Bank of India           976
5              Infosys           970
6     Bharat Petroleum           969
7             Flipkart           966
8              PhonePe           965
9                Wipro           964

In [6]:
from collections import Counter

all_skills = []

for skills in df['skills_required']:
    if pd.notna(skills):
        skill_list = skills.lower().split(',')
        all_skills.extend([s.strip() for s in skill_list])

skill_demand = Counter(all_skills)

top_skills = pd.DataFrame(
    skill_demand.most_common(10),
    columns=['Skill', 'Demand_Count']
)

top_skills

             Skill  Demand_Count
0    communication         16845
1  problem solving         16845
2        team work         16845
3           python          7461
4              sql          5627
5            excel          3811
6         power bi          3811
7             java          3743
8  data structures          1927
9             oops          1927

In [ ]:
location_demand = (
    df['city']
    .value_counts()
    .reset_index()
)

location_demand.columns = ['Location', 'Job_Count']
                                                                                                                                                                                          
top_locations = location_demand.head(10)

top_locations

    Location  Job_Count
0  Bangalore       3070
1      Delhi       3063
2  Ahmedabad       3049
3    Chennai       2999
4   Gurugram       2996
5      Noida       2984
6     Mumbai       2973
7  Hyderabad       2964
8    Kolkata       2962
9       Pune       2940

In [9]:
experience_demand = (
    df['experience_level']
    .value_counts()
    .reset_index()
)

experience_demand.columns = ['Experience_Level', 'Job_Count']

experience_demand

  Experience_Level  Job_Count
0        3-5 years       5101
1        0-1 years       5072
2        5-8 years       5046
3       8-12 years       4948
4        1-3 years       4924
5        12+ years       4909

In [23]:
salary_by_exp = (
    df.groupby('experience_level')['salary_inr']
    .mean()
    .reset_index()
)

# Convert INR to LPA and round to nearest whole number
salary_by_exp['salary_lpa'] = (salary_by_exp['salary_inr'] / 100000).round(0).astype(int)

salary_by_exp

  experience_level    salary_inr  salary_lpa
0        0-1 years  1.302495e+06          13
1        1-3 years  1.301732e+06          13
2        12+ years  1.299456e+06          13
3        3-5 years  1.288175e+06          13
4        5-8 years  1.296949e+06          13
5       8-12 years  1.276747e+06          13